# Generated by Django 3.2.9 on 2022-02-16 07:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_manager_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Max length 200 character', max_length=200, null=True, verbose_name='about_manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_manager_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Max length 200 character', max_length=200, null=True, verbose_name='about_manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_manager_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Max length 200 character', max_length=200, null=True, verbose_name='about_manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch_address',
            field=models.TextField(blank=True, help_text='Max length 100 character', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Max length 50 character', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='co_address',
            field=models.TextField(blank=True, help_text='Max length 100 character', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='co_country_registered',
            field=models.CharField(blank=True, help_text='Max length 20 character', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='co_website_address',
            field=models.CharField(blank=True, help_text='Max length 40 character', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Max length 25 character', max_length=25),
        ),
    ]
