# Generated by Django 3.2.9 on 2022-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
