# Generated by Django 3.2.9 on 2022-02-12 08:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True, verbose_name='slug (Link)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/category')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': '02. News Category',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': '03. News Tag',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='news/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'published'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('author', models.ForeignKey(limit_choices_to={'is_author': True}, on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, related_name='news', to='news.CategoryNews')),
                ('tag', models.ManyToManyField(blank=True, related_name='news_tag', to='news.NewsTag')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': '01. News',
                'ordering': ('-created_at',),
            },
        ),
    ]
