# Generated by Django 3.2.9 on 2022-02-12 08:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Raw material', 'Raw material'), ('Life style', 'Life style')], max_length=15)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': '1. Messages',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Raw material', 'Raw material'), ('Life style', 'Life style')], max_length=15)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': '2. Subscribers',
            },
        ),
    ]
