# Generated by Django 3.2.9 on 2022-02-12 08:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_it', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_it', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': '1. Pages',
            },
        ),
    ]
