# Generated by Django 3.2.9 on 2022-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='title_en',
            field=models.CharField(help_text='Max length 50 character', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title_it',
            field=models.CharField(help_text='Max length 50 character', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title_ru',
            field=models.CharField(help_text='Max length 50 character', max_length=50, null=True, verbose_name='title'),
        ),
    ]
