# Generated by Django 3.2.9 on 2022-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='retail_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='%'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='wholesale_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='%'),
        ),
    ]
