# Generated by Django 3.2.9 on 2022-02-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='admin_logo',
            field=models.ImageField(default='0', upload_to='main/logo'),
        ),
    ]
