# Generated by Django 3.2.9 on 2022-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesetting_admin_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='admin_logo',
            field=models.ImageField(help_text='Logo color should be "Dark"', upload_to='main/logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='main/favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(help_text='Logo color should be "Light"', upload_to='main/logo'),
        ),
    ]
