# Generated by Django 3.2.9 on 2022-02-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220214_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Max length 160 character', max_length=160, null=True),
        ),
    ]
