# Generated by Django 3.2.9 on 2022-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesetting_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsslider',
            name='page',
        ),
        migrations.RemoveField(
            model_name='maincategories',
            name='page',
        ),
        migrations.RemoveField(
            model_name='mainnavbar',
            name='page',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='page',
        ),
        migrations.RemoveField(
            model_name='subnavbar',
            name='page',
        ),
    ]
