# Generated by Django 3.2.9 on 2022-02-16 07:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220214_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategories',
            name='link',
            field=models.CharField(help_text='Max length 30 character', max_length=30),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='title_en',
            field=models.CharField(help_text='Max length 10 character', max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='title_it',
            field=models.CharField(help_text='Max length 10 character', max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='title_ru',
            field=models.CharField(help_text='Max length 10 character', max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='city',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='country',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='first_name',
            field=models.CharField(help_text='Max length 30 character', max_length=30),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='last_name',
            field=models.CharField(help_text='Max length 30 character', max_length=30),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='zip_code',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='link',
            field=models.CharField(help_text='Max length 50 character', max_length=50),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='title_en',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='title_it',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='title_ru',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='specialprojects',
            name='link',
            field=models.CharField(help_text='Max length 50 character', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialprojects',
            name='title_en',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='specialprojects',
            name='title_it',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='specialprojects',
            name='title_ru',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='country',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='description_en',
            field=ckeditor.fields.RichTextField(help_text='Max length 200 character', max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='description_it',
            field=ckeditor.fields.RichTextField(help_text='Max length 200 character', max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='description_ru',
            field=ckeditor.fields.RichTextField(help_text='Max length 200 character', max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='name_en',
            field=models.CharField(help_text='Max length 25 character', max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='name_it',
            field=models.CharField(help_text='Max length 25 character', max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storeagent',
            name='name_ru',
            field=models.CharField(help_text='Max length 25 character', max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='link',
            field=models.CharField(help_text='Max length 50 character', max_length=50),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='title_en',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='title_it',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='title_ru',
            field=models.CharField(help_text='Max length 15 character', max_length=15, verbose_name='title'),
        ),
    ]
