# Generated by Django 3.2.9 on 2022-02-16 07:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Max length 250 character', max_length=250),
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(help_text='Max length 25 character', max_length=25),
        ),
    ]
