# Generated by Django 3.2.9 on 2022-02-12 08:44

import config.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': '05. Products Material',
            },
        ),
        migrations.CreateModel(
            name='ProductPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='%')),
                ('slug', models.SlugField(help_text="Don't change this field", unique=True)),
            ],
            options={
                'verbose_name': 'percent',
                'verbose_name_plural': '07. Product price percent',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=50, verbose_name='title')),
                ('title_ru', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='Slug (URL)')),
                ('image', models.ImageField(blank=True, help_text='(1600 * 250)px', null=True, upload_to='products/category', validators=[config.validators.validate_file_size])),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productscategory')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': '02. Products Category',
                'ordering': ('parent__id',),
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': '08. Product size',
            },
        ),
        migrations.CreateModel(
            name='ProductsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': '04. Products Tag',
            },
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': '03. Products Type',
            },
        ),
        migrations.CreateModel(
            name='ShoeSole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sole',
                'verbose_name_plural': '06. Shoe sole',
            },
        ),
        migrations.CreateModel(
            name='ShowProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_retail_price', models.BooleanField(default=True)),
                ('show_wholesale_price', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, limit_choices_to={'is_seller': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productscategory')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': '09. Products show/hide status',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=450, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('code1', models.CharField(max_length=20, verbose_name='Supplier code')),
                ('code2', models.CharField(max_length=50, unique=True, verbose_name='Product code')),
                ('model', models.CharField(max_length=50, verbose_name='Product model')),
                ('size_info', models.TextField(blank=True, null=True, verbose_name='Size more information')),
                ('care_info', models.TextField(blank=True, max_length=500, null=True)),
                ('care_and_fabric', models.TextField(blank=True, max_length=300, null=True)),
                ('finer_detail', models.TextField(blank=True, max_length=300, null=True)),
                ('heel', models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True)),
                ('sole', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='gr', null=True, verbose_name='Product weight')),
                ('dimensions', models.TextField(blank=True, help_text='Dimensions', max_length=250, null=True)),
                ('exw_price', models.CharField(max_length=50)),
                ('wholesale_price', models.CharField(max_length=20)),
                ('retail_price_USD', models.CharField(max_length=20)),
                ('retail_price_EUR', models.CharField(max_length=20)),
                ('retail_price_RUB', models.CharField(max_length=20)),
                ('retail_price_SAR', models.CharField(max_length=20)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('wholesale_discount', models.PositiveSmallIntegerField(default=0)),
                ('retail_discount', models.PositiveSmallIntegerField(default=0)),
                ('show_discount', models.BooleanField(default=True)),
                ('currency', models.CharField(choices=[('us_dollar', 'US Dollar'), ('ir_rials', 'IR Rials'), ('ruble', 'Ruble'), ('euro', 'Euro')], max_length=10)),
                ('show_retail_price', models.BooleanField(default=True)),
                ('show_wholesale_price', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='product/', validators=[config.validators.validate_file_size])),
                ('status', models.CharField(choices=[('published', 'published'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('category', models.ManyToManyField(related_name='c_products', to='products.ProductsCategory')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_products', to='products.productmaterial')),
                ('seller', models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='s_products', to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(blank=True, related_name='s_products', to='products.ProductSize', verbose_name='Product Size')),
                ('tag', models.ManyToManyField(blank=True, related_name='t_products', to='products.ProductsTag')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': '01. Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images', validators=[config.validators.validate_file_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='PriceIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=0, max_length=15)),
                ('all_products', models.BooleanField(default=False, verbose_name='Increase on all the products?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productscategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_increase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': '10. Price increase',
                'ordering': ('-created_at',),
            },
        ),
    ]
