# Generated by Django 3.2.9 on 2022-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='retail_price_EUR',
        ),
        migrations.RemoveField(
            model_name='products',
            name='retail_price_RUB',
        ),
        migrations.RemoveField(
            model_name='products',
            name='retail_price_SAR',
        ),
    ]
