# Generated by Django 3.2.9 on 2022-02-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='title',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='productpercent',
            name='slug',
            field=models.CharField(choices=[('retailer', 'retailer'), ('wholesale', 'wholesale')], help_text="Don't change this field", max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='care_and_fabric',
            field=models.TextField(blank=True, help_text='Max length 100 character', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='care_info',
            field=models.TextField(blank=True, help_text='Max length 100 character', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='code2',
            field=models.CharField(max_length=7, unique=True, verbose_name='Product code'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, help_text='Max length 250 character', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='dimensions',
            field=models.TextField(blank=True, help_text='Max length 50 character', max_length=50, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='products',
            name='finer_detail',
            field=models.TextField(blank=True, help_text='Max length 100 character', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(max_length=10, verbose_name='Product model'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(help_text='Max length 25 character', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(help_text='Max length 20 character', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='title_en',
            field=models.CharField(help_text='Max length 20 character', max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='title_it',
            field=models.CharField(help_text='Max length 20 character', max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='title_ru',
            field=models.CharField(help_text='Max length 20 character', max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productstag',
            name='title',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='productstype',
            name='title',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoesole',
            name='title',
            field=models.CharField(help_text='Max length 20 character', max_length=20),
        ),
    ]
